#version : "3.8"
services:
  book-service:
    build: ./book-service
    image: book-service:latest
    container_name: book-service
    ports:
      - 3000:3000
    networks:
      - app-network
    environment:
      - DATABASE_URL=mongodb://book-service-db:27017/books
    depends_on:
      - book-service-db

  book-service-db:
    image: mongo:latest
    container_name: book-services-db
    # to make the db accessible via the host port, eg: when working with
    #compass
    ports:
      - "27018:27017"
    networks:
      - app-network
    # maps the mongo-data volume on the host to the data/db on the container
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
networks:
  app-network:
    driver: bridge
